### ISSUE TITLE
ran SAMPLE and failed 

### ISSUE THREAD

**Issue by Hanxi0124** [DezerteR/D_star_PathPlanning#1]
**Every time I run SAMPLE, it fails and shows as below. What should I do with  DStarcmp.class? Can anyone help me with it? Thanks!**

```
Undefined function or variable 'DStarcmp'.

Error in FDSInit (line 50)
    out.comparator = DStarcmp;

Error in SAMPLE (line 38)
        state = FDSInit(start, goal, maps{1}, scalling);
```

**Comment by LazyFalcon** [comment]
Unfortunately I don't own Matlab license anymore. Which version are you using? IIRC it was written in something around v2013.

**Comment by Hanxi0124** [comment]
Thanks for your reply! I am using MATLAB 2016a and I will try v2013. BTW, do I need to install any package before I run SAMPLE?

**Comment by LazyFalcon** [comment]
Ah, I remember, first java should be called in this folder. I'm using priority queue from java which gives nice performance boost.
```
%% init java, run at begin, once
% necessary to  load java files
% clear java
% javaclasspath(pwd)
```
But I don't remember how exactly use it, I didn't use it since I was a student.

**Comment by Hanxi0124** [comment]
That's really important! Don't worry I will try it out. Thanks for your reminder!

**Comment by Hanxi0124** [comment]
I just ran the this code and it works!  `javaclasspath(pwd);`  Thanks a lot for the tip!

**Comment by LazyFalcon** [comment]
Great!
