### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mshtmled** [DezerteR/D_star_PathPlanning#2]
there is a warning, undefined variable DStarcmp, what is wrong with the oringinal code??

未定义函数或变量 'DStarcmp'。

出错 FDSInit (line 50)
    out.comparator = DStarcmp;

出错 SAMPLE (line 38)
        state = FDSInit(start, goal, maps{1}, scalling);

**Comment by LazyFalcon** [comment]
Please refer to #1
